[package]
name = "bike_station"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.22.0", features = ["macros"]}
tokio-postgres = "0.7.7"
agrum = { path = "../../" }
