[package]
name = "bike_station"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.22.0", features = ["macros"]}
tokio-postgres = { version = "0.7.7", features = ["with-geo-types-0_7"] }
agrum = { path = "../../" }
geo-types = "0.7.8"
comfy-table = "6.1.4"

