name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install PG
      run: |
        sudo apt install postgres
        sudo su -c "createuser agrum" - postgres
        sudo su -c 'createdb -O agrum agrum' - postgres
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
